/*
 * Generated by TASKING Pin Mapper for AURIX
 * - device  : TC39XEDB
 * - package : LFBGA292
 */

/*
 * Instructions on how to build this generated file and the Infineon's iLLD library with the TASKING  VX-toolset
 * for TriCore:
 * 1. Provide appropriate include paths to the compiler (-I option) to locate the iLLD library.
 * 2. Provide macro IFX_CFG_USE_COMPILER_DEFAULT_LINKER to the compiler (-D option) to prevent multiple
 *    definitions of symbol '_START' (in cstart.c and IfxCpu_CStart0.c).
 * 3. Disable compiler option 'Automatic inclusion of .sfr files' (-H option) to prevent macros to be redefined.
 */

#ifndef AURIX_PIN_MAPPINGS_H_
#define AURIX_PIN_MAPPINGS_H_

/* Infineon's iLLD library include files */

#include <Port/Io/IfxPort_Io.h>

#include <_PinMap/IfxPort_PinMap.h>


/* Symbolic names for GPIO ports */

// p14_0
#define IFXCFG_PORT_PT_A_DRVEN                  IfxPort_P14_0
#define IFXCFG_PORT_PT_A_DRVEN_MODE             IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PT_A_DRVEN_PAD_DRIVER       IfxPort_PadDriver_cmosAutomotiveSpeed4

// p14_6
#define IFXCFG_PORT_PT_A_DBG                    IfxPort_P14_6
#define IFXCFG_PORT_PT_A_DBG_MODE               IfxPort_Mode_inputPullUp
#define IFXCFG_PORT_PT_A_DBG_PAD_DRIVER         IfxPort_PadDriver_cmosAutomotiveSpeed1

// p14_9
#define IFXCFG_PORT_PT_A_NRST                   IfxPort_P14_9
#define IFXCFG_PORT_PT_A_NRST_MODE              IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PT_A_NRST_PAD_DRIVER        IfxPort_PadDriver_cmosAutomotiveSpeed4

// p15_0
#define IFXCFG_PORT_PT_A_START6                 IfxPort_P15_0
#define IFXCFG_PORT_PT_A_START6_MODE            IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PT_A_START6_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed4

// p15_1
#define IFXCFG_PORT_PT_A_START3                 IfxPort_P15_1
#define IFXCFG_PORT_PT_A_START3_MODE            IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PT_A_START3_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed4

// p15_2
#define IFXCFG_PORT_PT_A_START5                 IfxPort_P15_2
#define IFXCFG_PORT_PT_A_START5_MODE            IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PT_A_START5_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed4

// p15_3
#define IFXCFG_PORT_PT_A_START2                 IfxPort_P15_3
#define IFXCFG_PORT_PT_A_START2_MODE            IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PT_A_START2_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed4

// p15_4
#define IFXCFG_PORT_PT_A_START1                 IfxPort_P15_4
#define IFXCFG_PORT_PT_A_START1_MODE            IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PT_A_START1_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed4

// p15_5
#define IFXCFG_PORT_PT_A_START4                 IfxPort_P15_5
#define IFXCFG_PORT_PT_A_START4_MODE            IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PT_A_START4_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed4

// p20_9
#define IFXCFG_PORT_PT_A_START7                 IfxPort_P20_9
#define IFXCFG_PORT_PT_A_START7_MODE            IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PT_A_START7_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed4

// p22_1
#define IFXCFG_PORT_PT_B_NRST                   IfxPort_P22_1
#define IFXCFG_PORT_PT_B_NRST_MODE              IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PT_B_NRST_PAD_DRIVER        IfxPort_PadDriver_cmosAutomotiveSpeed4

// p22_3
#define IFXCFG_PORT_PT_B_DBG                    IfxPort_P22_3
#define IFXCFG_PORT_PT_B_DBG_MODE               IfxPort_Mode_inputPullUp
#define IFXCFG_PORT_PT_B_DBG_PAD_DRIVER         IfxPort_PadDriver_cmosAutomotiveSpeed1

// p22_5
#define IFXCFG_PORT_HSD01_LL                    IfxPort_P22_5
#define IFXCFG_PORT_HSD01_LL_MODE               IfxPort_Mode_inputPullUp
#define IFXCFG_PORT_HSD01_LL_PAD_DRIVER         IfxPort_PadDriver_cmosAutomotiveSpeed1

// p22_10
#define IFXCFG_PORT_HSD01_EN                    IfxPort_P22_10
#define IFXCFG_PORT_HSD01_EN_MODE               IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_HSD01_EN_PAD_DRIVER         IfxPort_PadDriver_cmosAutomotiveSpeed4

// p22_11
#define IFXCFG_PORT_HSD01_DIAG1                 IfxPort_P22_11
#define IFXCFG_PORT_HSD01_DIAG1_MODE            IfxPort_Mode_inputPullUp
#define IFXCFG_PORT_HSD01_DIAG1_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed1

// p23_1
#define IFXCFG_PORT_HSD02_EN                    IfxPort_P23_1
#define IFXCFG_PORT_HSD02_EN_MODE               IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_HSD02_EN_PAD_DRIVER         IfxPort_PadDriver_cmosAutomotiveSpeed4

// p23_2
#define IFXCFG_PORT_HSD02_LL                    IfxPort_P23_2
#define IFXCFG_PORT_HSD02_LL_MODE               IfxPort_Mode_inputPullUp
#define IFXCFG_PORT_HSD02_LL_PAD_DRIVER         IfxPort_PadDriver_cmosAutomotiveSpeed1

// p23_3
#define IFXCFG_PORT_HSD01_DIAG2                 IfxPort_P23_3
#define IFXCFG_PORT_HSD01_DIAG2_MODE            IfxPort_Mode_inputPullUp
#define IFXCFG_PORT_HSD01_DIAG2_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed1

// p23_4
#define IFXCFG_PORT_HSD02_DIAG1                 IfxPort_P23_4
#define IFXCFG_PORT_HSD02_DIAG1_MODE            IfxPort_Mode_inputPullUp
#define IFXCFG_PORT_HSD02_DIAG1_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed1

// p23_5
#define IFXCFG_PORT_LED4                        IfxPort_P23_5
#define IFXCFG_PORT_LED4_MODE                   IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_LED4_PAD_DRIVER             IfxPort_PadDriver_cmosAutomotiveSpeed4

// p23_6
#define IFXCFG_PORT_HSD02_DIAG2                 IfxPort_P23_6
#define IFXCFG_PORT_HSD02_DIAG2_MODE            IfxPort_Mode_inputPullUp
#define IFXCFG_PORT_HSD02_DIAG2_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed1

// p23_7
#define IFXCFG_PORT_LED3                        IfxPort_P23_7
#define IFXCFG_PORT_LED3_MODE                   IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_LED3_PAD_DRIVER             IfxPort_PadDriver_cmosAutomotiveSpeed4

// p32_2
#define IFXCFG_PORT_LED2                        IfxPort_P32_2
#define IFXCFG_PORT_LED2_MODE                   IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_LED2_PAD_DRIVER             IfxPort_PadDriver_cmosAutomotiveSpeed4

// p32_3
#define IFXCFG_PORT_LED1                        IfxPort_P32_3
#define IFXCFG_PORT_LED1_MODE                   IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_LED1_PAD_DRIVER             IfxPort_PadDriver_cmosAutomotiveSpeed4

// p33_4
#define IFXCFG_PORT_PT_B_START6                 IfxPort_P33_4
#define IFXCFG_PORT_PT_B_START6_MODE            IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PT_B_START6_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed4

// p33_6
#define IFXCFG_PORT_PT_B_START7                 IfxPort_P33_6
#define IFXCFG_PORT_PT_B_START7_MODE            IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PT_B_START7_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed4

// p33_10
#define IFXCFG_PORT_PT_B_START4                 IfxPort_P33_10
#define IFXCFG_PORT_PT_B_START4_MODE            IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PT_B_START4_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed4

// p33_11
#define IFXCFG_PORT_PT_B_START5                 IfxPort_P33_11
#define IFXCFG_PORT_PT_B_START5_MODE            IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PT_B_START5_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed4

// p33_12
#define IFXCFG_PORT_PT_B_START1                 IfxPort_P33_12
#define IFXCFG_PORT_PT_B_START1_MODE            IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PT_B_START1_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed4

// p33_13
#define IFXCFG_PORT_PT_B_START2                 IfxPort_P33_13
#define IFXCFG_PORT_PT_B_START2_MODE            IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PT_B_START2_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed4

// p33_14
#define IFXCFG_PORT_PT_B_DRVEN                  IfxPort_P33_14
#define IFXCFG_PORT_PT_B_DRVEN_MODE             IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PT_B_DRVEN_PAD_DRIVER       IfxPort_PadDriver_cmosAutomotiveSpeed4

// p33_15
#define IFXCFG_PORT_PT_B_START3                 IfxPort_P33_15
#define IFXCFG_PORT_PT_B_START3_MODE            IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PT_B_START3_PAD_DRIVER      IfxPort_PadDriver_cmosAutomotiveSpeed4


/* Generic port I/O configuration */

#define IFXCFG_P14_0_IO_CONFIG                  { &IFXCFG_PORT_PT_A_DRVEN, IFXCFG_PORT_PT_A_DRVEN_MODE, IFXCFG_PORT_PT_A_DRVEN_PAD_DRIVER }
#define IFXCFG_P14_6_IO_CONFIG                  { &IFXCFG_PORT_PT_A_DBG, IFXCFG_PORT_PT_A_DBG_MODE, IFXCFG_PORT_PT_A_DBG_PAD_DRIVER }
#define IFXCFG_P14_9_IO_CONFIG                  { &IFXCFG_PORT_PT_A_NRST, IFXCFG_PORT_PT_A_NRST_MODE, IFXCFG_PORT_PT_A_NRST_PAD_DRIVER }
#define IFXCFG_P15_0_IO_CONFIG                  { &IFXCFG_PORT_PT_A_START6, IFXCFG_PORT_PT_A_START6_MODE, IFXCFG_PORT_PT_A_START6_PAD_DRIVER }
#define IFXCFG_P15_1_IO_CONFIG                  { &IFXCFG_PORT_PT_A_START3, IFXCFG_PORT_PT_A_START3_MODE, IFXCFG_PORT_PT_A_START3_PAD_DRIVER }
#define IFXCFG_P15_2_IO_CONFIG                  { &IFXCFG_PORT_PT_A_START5, IFXCFG_PORT_PT_A_START5_MODE, IFXCFG_PORT_PT_A_START5_PAD_DRIVER }
#define IFXCFG_P15_3_IO_CONFIG                  { &IFXCFG_PORT_PT_A_START2, IFXCFG_PORT_PT_A_START2_MODE, IFXCFG_PORT_PT_A_START2_PAD_DRIVER }
#define IFXCFG_P15_4_IO_CONFIG                  { &IFXCFG_PORT_PT_A_START1, IFXCFG_PORT_PT_A_START1_MODE, IFXCFG_PORT_PT_A_START1_PAD_DRIVER }
#define IFXCFG_P15_5_IO_CONFIG                  { &IFXCFG_PORT_PT_A_START4, IFXCFG_PORT_PT_A_START4_MODE, IFXCFG_PORT_PT_A_START4_PAD_DRIVER }
#define IFXCFG_P20_9_IO_CONFIG                  { &IFXCFG_PORT_PT_A_START7, IFXCFG_PORT_PT_A_START7_MODE, IFXCFG_PORT_PT_A_START7_PAD_DRIVER }
#define IFXCFG_P22_1_IO_CONFIG                  { &IFXCFG_PORT_PT_B_NRST, IFXCFG_PORT_PT_B_NRST_MODE, IFXCFG_PORT_PT_B_NRST_PAD_DRIVER }
#define IFXCFG_P22_3_IO_CONFIG                  { &IFXCFG_PORT_PT_B_DBG, IFXCFG_PORT_PT_B_DBG_MODE, IFXCFG_PORT_PT_B_DBG_PAD_DRIVER }
#define IFXCFG_P22_5_IO_CONFIG                  { &IFXCFG_PORT_HSD01_LL, IFXCFG_PORT_HSD01_LL_MODE, IFXCFG_PORT_HSD01_LL_PAD_DRIVER }
#define IFXCFG_P22_10_IO_CONFIG                 { &IFXCFG_PORT_HSD01_EN, IFXCFG_PORT_HSD01_EN_MODE, IFXCFG_PORT_HSD01_EN_PAD_DRIVER }
#define IFXCFG_P22_11_IO_CONFIG                 { &IFXCFG_PORT_HSD01_DIAG1, IFXCFG_PORT_HSD01_DIAG1_MODE, IFXCFG_PORT_HSD01_DIAG1_PAD_DRIVER }
#define IFXCFG_P23_1_IO_CONFIG                  { &IFXCFG_PORT_HSD02_EN, IFXCFG_PORT_HSD02_EN_MODE, IFXCFG_PORT_HSD02_EN_PAD_DRIVER }
#define IFXCFG_P23_2_IO_CONFIG                  { &IFXCFG_PORT_HSD02_LL, IFXCFG_PORT_HSD02_LL_MODE, IFXCFG_PORT_HSD02_LL_PAD_DRIVER }
#define IFXCFG_P23_3_IO_CONFIG                  { &IFXCFG_PORT_HSD01_DIAG2, IFXCFG_PORT_HSD01_DIAG2_MODE, IFXCFG_PORT_HSD01_DIAG2_PAD_DRIVER }
#define IFXCFG_P23_4_IO_CONFIG                  { &IFXCFG_PORT_HSD02_DIAG1, IFXCFG_PORT_HSD02_DIAG1_MODE, IFXCFG_PORT_HSD02_DIAG1_PAD_DRIVER }
#define IFXCFG_P23_5_IO_CONFIG                  { &IFXCFG_PORT_LED4, IFXCFG_PORT_LED4_MODE, IFXCFG_PORT_LED4_PAD_DRIVER }
#define IFXCFG_P23_6_IO_CONFIG                  { &IFXCFG_PORT_HSD02_DIAG2, IFXCFG_PORT_HSD02_DIAG2_MODE, IFXCFG_PORT_HSD02_DIAG2_PAD_DRIVER }
#define IFXCFG_P23_7_IO_CONFIG                  { &IFXCFG_PORT_LED3, IFXCFG_PORT_LED3_MODE, IFXCFG_PORT_LED3_PAD_DRIVER }
#define IFXCFG_P32_2_IO_CONFIG                  { &IFXCFG_PORT_LED2, IFXCFG_PORT_LED2_MODE, IFXCFG_PORT_LED2_PAD_DRIVER }
#define IFXCFG_P32_3_IO_CONFIG                  { &IFXCFG_PORT_LED1, IFXCFG_PORT_LED1_MODE, IFXCFG_PORT_LED1_PAD_DRIVER }
#define IFXCFG_P33_4_IO_CONFIG                  { &IFXCFG_PORT_PT_B_START6, IFXCFG_PORT_PT_B_START6_MODE, IFXCFG_PORT_PT_B_START6_PAD_DRIVER }
#define IFXCFG_P33_6_IO_CONFIG                  { &IFXCFG_PORT_PT_B_START7, IFXCFG_PORT_PT_B_START7_MODE, IFXCFG_PORT_PT_B_START7_PAD_DRIVER }
#define IFXCFG_P33_10_IO_CONFIG                 { &IFXCFG_PORT_PT_B_START4, IFXCFG_PORT_PT_B_START4_MODE, IFXCFG_PORT_PT_B_START4_PAD_DRIVER }
#define IFXCFG_P33_11_IO_CONFIG                 { &IFXCFG_PORT_PT_B_START5, IFXCFG_PORT_PT_B_START5_MODE, IFXCFG_PORT_PT_B_START5_PAD_DRIVER }
#define IFXCFG_P33_12_IO_CONFIG                 { &IFXCFG_PORT_PT_B_START1, IFXCFG_PORT_PT_B_START1_MODE, IFXCFG_PORT_PT_B_START1_PAD_DRIVER }
#define IFXCFG_P33_13_IO_CONFIG                 { &IFXCFG_PORT_PT_B_START2, IFXCFG_PORT_PT_B_START2_MODE, IFXCFG_PORT_PT_B_START2_PAD_DRIVER }
#define IFXCFG_P33_14_IO_CONFIG                 { &IFXCFG_PORT_PT_B_DRVEN, IFXCFG_PORT_PT_B_DRVEN_MODE, IFXCFG_PORT_PT_B_DRVEN_PAD_DRIVER }
#define IFXCFG_P33_15_IO_CONFIG                 { &IFXCFG_PORT_PT_B_START3, IFXCFG_PORT_PT_B_START3_MODE, IFXCFG_PORT_PT_B_START3_PAD_DRIVER }


/* Generic alternate I/O configuration */

// qspi1_m
#define IFXCFG_P10_1_IO_CONFIG                  { &IfxPort_P10_1, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P10_2_IO_CONFIG                  { &IfxPort_P10_2, IfxPort_Mode_outputPushPullAlt3, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P10_3_IO_CONFIG                  { &IfxPort_P10_3, IfxPort_Mode_outputPushPullAlt3, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P10_4_IO_CONFIG                  { &IfxPort_P10_4, IfxPort_Mode_outputPushPullAlt3, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// qspi3_m
#define IFXCFG_P01_4_IO_CONFIG                  { &IfxPort_P01_4, IfxPort_Mode_outputPushPullAlt4, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P01_5_IO_CONFIG                  { &IfxPort_P01_5, IfxPort_Mode_inputPullUp, IfxPort_PadDriver_cmosAutomotiveSpeed1 }
#define IFXCFG_P01_6_IO_CONFIG                  { &IfxPort_P01_6, IfxPort_Mode_outputPushPullAlt4, IfxPort_PadDriver_cmosAutomotiveSpeed4 }
#define IFXCFG_P01_7_IO_CONFIG                  { &IfxPort_P01_7, IfxPort_Mode_outputPushPullAlt4, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// tout11
#define IFXCFG_P00_2_IO_CONFIG                  { &IfxPort_P00_2, IfxPort_Mode_outputPushPullAlt1, IfxPort_PadDriver_cmosAutomotiveSpeed4 }

// tout19
#define IFXCFG_P00_10_IO_CONFIG                 { &IfxPort_P00_10, IfxPort_Mode_outputPushPullAlt1, IfxPort_PadDriver_cmosAutomotiveSpeed4 }


/* Initialization routines */

extern void gpio_init_pins(void);

extern void qspi1_m_init_pins(void);

extern void qspi3_m_init_pins(void);

extern void tout11_init_pins(void);

extern void tout19_init_pins(void);


#endif /* AURIX_PIN_MAPPINGS_H_ */
